name: Run unit tests, merge develop into master and push

on:
  push:
    branches: [develop]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Pull repository into the current pipeline
      - name: Pull repository
        uses: actions/checkout@v2

      - name: NPM install
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Merge develop into master and push
        run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge develop -m "Auto merge dev into master"
          git push
